[package]
name = "quad-snd"
version = "0.1.1"
authors = ["not-fl3 <not.fl3@gmail.com>"]
description = "Unrust low level native/wasm compatibility layer for sound output"
license = "MIT"
documentation = "https://docs.rs/quad-snd"
repository = "https://github.com/not-fl3/quad-snd"
keywords = ["sound", "wasm"]
edition = "2018"

[dependencies]
hound = "*"
lewton = "*"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal= "0.11.0"

[dev-dependencies]
macroquad = "0.2.0-alpha.0"
